### ISSUE TITLE
AirConnect not compatible with Synology DSM 7 final

### ISSUE THREAD

**Issue by Spy-1** [eizedev/AirConnect-Synology#24] opened 2021-06-29 09:02 UTC
Installed the final DSM V41890 today.
Unfortunately AirConnect is not compatible and is stopped.

**Comment by eizedev** [comment] 2021-06-30 20:30
@Spy-1 thanks for reporting this. We already have an issue for the dsm7 compatibility. Take a look at #12.
I will close this issue as an duplicate of #12.

**Closed by eizedev** 2021-06-30 20:30 UTC
Labels: enhancement
