### ISSUE TITLE
[BUG] Not sure if compatible with DSM 7

### ISSUE THREAD

**Issue by jaspreetsidhu** [eizedev/AirConnect-Synology#12] opened 2021-01-05 06:08 UTC
**Describe the bug**
Upon installation on DS1621+ running Beta DSM 7, receive Invalid file format. Please contact developer message.
**To Reproduce**
See above
**Expected behavior**
Installation to proceed
**Logfiles**

**Hardware (Device on which you are running AirConnect-Synology):**
 - DS1621+
 - DSM 7 Beta

**Package (which package from the [releases](https://github.com/eizedev/AirConnect-Synology/releases) page have you downloaded):**
0.2.43.0-20201229

**Comment by eizedev** [comment] 2021-01-05 09:01
I had a quick look at the [DSM7 Beta Developer Guidelines](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/7.0/enu/DSM_Developer_Guide_7_0_Beta.pdf) but couldn't see much difference at first glance (page 35 ++). I have to take a closer look at this in peace.
Thanks for testing and reporting the bug.

**Comment by pianshanchou** [comment] 2021-04-03 17:50
I have the same problem, it is not available in version 7.

**Comment by eizedev** [comment] 2021-04-06 08:23
Thanks for reporting.
The build process for packages in dsm7 (the package structure) has changed, therefore I have to adapt the packages for DSM 7.
Since I don't install DSM beta software, it will take some time before I can test it. But in the next weeks I will develop a first test version based on the documentation and make it available here for testing.

**Comment by j6s33m** [comment] 2021-04-13 19:10
> Thanks for reporting.
> The build process for packages in dsm7 (the package structure) has changed, therefore I have to adapt the packages for DSM 7.
> Since I don't install DSM beta software, it will take some time before I can test it. But in the next weeks I will develop a first test version based on the documentation and make it available here for testing.

Will be happy to beta test this for DSM7

**Comment by fabi86** [comment] 2021-04-17 13:45
Same here, available fpr beta test

**Comment by j6s33m** [comment] 2021-05-28 15:17
> Thanks for reporting.
> The build process for packages in dsm7 (the package structure) has changed, therefore I have to adapt the packages for DSM 7.
> Since I don't install DSM beta software, it will take some time before I can test it. But in the next weeks I will develop a first test version based on the documentation and make it available here for testing.

Any updates in the dev of this beta?

**Comment by eizedev** [comment] 2021-05-30 19:57
Nothing new yet. But i will share a new version for dsm7 in the next weeks

**Comment by Spy-1** [comment] 2021-06-29 12:26
Today there ist final of DSM 7 out.
Any news to reinstall airconnect on final DSM 7 ?

**Comment by eizedev** [comment] 2021-06-30 20:29
Sorry, no working version for now. Next weekend I want to take a closer look at it.

**Comment by kk62** [comment] 2021-07-03 16:58
If you don't wanna wait for a DSM7 Package.... go this way via Docker ... goes much easier...and works instantly !!
https://techbox.rocks/airconnect-airplay-fuer-aeltere-sonos-boxen-mit-hilfe-von-synology-nas/

regards kk62

**Comment by TsungShen** [comment] 2021-07-04 05:09
> If you don't wanna wait for a DSM7 Package.... go this way via Docker ... goes much easier...and works instantly !!
> https://techbox.rocks/airconnect-airplay-fuer-aeltere-sonos-boxen-mit-hilfe-von-synology-nas/
> 
> regards kk62

this way can work !
 but in the docker container setting, remember go the "network" tab to check the "use the network same docker host"

**Comment by Spy-1** [comment] 2021-07-04 05:22
It does not work for me. Not even if I use the same network as the Docker container.

**Comment by kk62** [comment] 2021-07-04 08:35
Hi Spy-1 . 

you must have done something wrong during the docker Installation. Follow the steps as mentioned in the Link:  https://techbox.rocks/airconnect-airplay-fuer-aeltere-sonos-boxen-mit-hilfe-von-synology-nas/ 

when you started the swilsonau/docker-airconnect Image - double click on the image - go to advanced settings  - click in the option use same network as docker host. and that it - after that you will see 2 container working in the container area swilsonau/docker-airconnect 1 + swilsonau/docker-airconnect 2. 

And in your Mac sound settings you will also see your Airplay devices after this - it works...
<img width="1075" alt="1" src="https://user-images.githubusercontent.com/70438971/124378744-6794e500-dcb3-11eb-91ab-ab903aa17a2e.png">


<img width="1264" alt="2" src="https://user-images.githubusercontent.com/70438971/124378750-6bc10280-dcb3-11eb-87a4-70b2e54e6f27.png">


<img width="1080" alt="3" src="https://user-images.githubusercontent.com/70438971/124378753-6fed2000-dcb3-11eb-9aee-34fc33bba397.png">

<img width="1314" alt="4" src="https://user-images.githubusercontent.com/70438971/124378758-754a6a80-dcb3-11eb-8ba5-30022c564fa5.png">


I hope I could help you this way..

**Comment by kk62** [comment] 2021-07-04 08:41
> > If you don't wanna wait for a DSM7 Package.... go this way via Docker ... goes much easier...and works instantly !!
> > https://techbox.rocks/airconnect-airplay-fuer-aeltere-sonos-boxen-mit-hilfe-von-synology-nas/
> > regards kk62
> 
> this way can work !
> but in the docker container setting, remember go the "network" tab to check the "use the network same docker host"

👍 :-) Nice that it worked for you...

**Comment by kk62** [comment] 2021-07-04 08:43
...by the way here is the docker hub original source if anybody is interested 

https://registry.hub.docker.com/r/swilsonau/docker-airconnect/

**Comment by eizedev** [comment] 2021-07-04 21:39
Hi,

**Please UNINSTALL your package first if it is still installed (or marked as repairable) after upgrading to dsm7.**

Sorry it took so long. I had a look at it for a few hours today and developed a working version for DSM7. 
I also fixed some existing bugs and would like to ask you, before the version is finally released, to test it on your DSM7 installations.
Both programs, `aircast` and `airupnp` will now run under the airconnect user. And the complete package will now fully managed from DSM (Before some parts were managed in the startup scripts).

Please give me a short feedback if it works for you and on which NAS you have installed it.

A few more notes on this release:

## New

- The package will create a new shared folder named **airconnect**, you can also find it via **FileStation**
  - In this folder you will find the airconnect logfile in the subdirectory `log`, so it is no longer necessary for normal use to log in via SSH to view the logfile.
    - The full path is `/volume1/airconnect/log/airconnect.log`
  -  Also, if you have a AirConnect configuration file for `airupnp` or `aircast` you could now copy this files also to the same directory in `/volume1/airconnect`, also using FileStation.
    - The files **must** be named as follows so that AirConnect can find the config files:
      - `config.xml` for airupnp
      - `config-cast.xml` for aircast
 - If you login using SSH, you can now start `airupnp` or `aircast` just by running `airupnp` or `aircast` without using the full path 
   - `airupnp` and `aircast` are now added to the PATH (symlinked using DSM config in `/usr/local/bin`) 

## Fixed

- Fixed the following issues in this release (will also be backported to dsm6):
  - #16
  - #22

## Download

You can download the pre-release here: [https://github.com/eizedev/AirConnect-Synology/releases/tag/dsm7-0.2.50.5](dsm7-0.2.50.5)

I have tested `AirConnect-dsm7-x86-0.2.50.5-20210704.spk` and `AirConnect-dsm7-x86-64-0.2.50.5-20210704.spk` on my devices.

## Additional Info

In one of the next releases you can also configure to only start `airupnp` or `aircast` (or both of them (Default)) using the package center GUI. But that is not currently included.
Also the ip address and the port airupnp will be started on, will be configurable using the GUI.

Example:

![image](https://user-images.githubusercontent.com/6794362/104040314-c895a180-51d7-11eb-8e65-21363a4679bf.png)

**Comment by Spy-1** [comment] 2021-07-05 06:47
Hi Rene,
first of all - it´s working for me (AirConnect-dsm7-x86-64-0.2.50.5-20210704.spk) on a synology DS920+ !
Thank you for your time and the really good work.
Waiting anxiously for the release and further development.

btw: the download Path above is not working.

**Comment by eizedev** [comment] 2021-07-05 07:09
thanks @Spy-1 
Link is fixed.

**Comment by eizedev** [comment] 2021-07-06 20:29
Please checkout the newest release [0.2.50.5-20210706 - DSM7 compatible](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.50.5-20210706) with Compatibility for DSM7, more security. It was also backported to DSM6 (tested) and DSM5 (untested).

If this release is working, we can then close this issue.

**Comment by Spy-1** [comment] 2021-07-07 06:21
Working for me! 👍

**Comment by Spy-1** [comment] 2021-07-09 10:14
Now, having the problem that streaming stops after a few minutes (1 -3)

**Comment by eizedev** [comment] 2021-07-09 14:29
@Spy-1 Could you please share the logfile or parts from the logfile? The logfile is now located in `/volume1/airconnect/log/airconnect.log`. Can also be found by using the FileStation.

**Comment by Spy-1** [comment] 2021-07-09 15:26
Her it is. Happend between 9 an 11 am . Streaming from Iphone via Apple Music to Sonos Büro.

 

Von: René ***@***.***> 
Gesendet: Freitag, 9. Juli 2021 16:29
An: eizedev/AirConnect-Synology ***@***.***>
Cc: Spy-1 ***@***.***>; Mention ***@***.***>
Betreff: Re: [eizedev/AirConnect-Synology] [BUG] Not sure if compatible with DSM 7 (#12)

 

@Spy-1 <https://github.com/Spy-1>  Could you please share the logfile or parts from the logfile? The logfile is now located in /volume1/airconnect/log/airconnect.log. Can also be found by using the FileStation.

**Comment by Spy-1** [comment] 2021-07-09 15:28
[airconnect.log](https://github.com/eizedev/AirConnect-Synology/files/6792397/airconnect.log)

**Comment by eizedev** [comment] 2021-07-11 11:02
@Spy-1 

The log file actually shows only a normal behavior in the mentioned time period.

Could you please test this package? It includes on older release of airupnp and aircast:
[/AirConnect-dsm7-x86-64-0.2.50.4-20210711.spk](https://github.com/eizedev/AirConnect-Synology/releases/download/0.2.50.4-20210711/AirConnect-dsm7-x86-64-0.2.50.4-20210711.spk)

I don't think the problem is related to our Synology package for DSM7.  I could not reproduce the problem on my end either. There could be a problem with the last update of the AirConnect package, then this older version should possibly work.

If this version is also not working, there could be a problem with the "flushing" behaviour of airupnp. Then you need to add `--flush` to the airupnp startup command.  (more information [here](https://github.com/philippe44/AirConnect/issues/234#issuecomment-797429477)). 
I could also build a package for you for testing if the above is not working.

**Comment by Spy-1** [comment] 2021-07-11 14:21
HI Rene, 
there was a network problem from my switch to the Sonos Boost (broken cable)
Now, after repairing this all works fine.

**Comment by eizedev** [comment] 2021-07-16 09:22
Since no further problems with the packages for DSM7 have been reported so far, I hereby close this issue. Please open a new issue if you have problems/questions/wishes.

**Closed by eizedev** 2021-07-16 09:22 UTC
Labels: dsm7, enhancement
